# fly.toml app configuration file generated for guild-league-discord-bot on 2024-05-27T22:45:01+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'guild-league-discord-bot'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
